// Generated by CoffeeScript 1.7.1
(function() {
  module.exports = function(_arg) {
    var Business, Candidate, Employer, Listing, User;
    User = _arg.User, Employer = _arg.Employer, Business = _arg.Business, Listing = _arg.Listing, Candidate = _arg.Candidate;
    return User.create({
      username: 'john.doe@domain.com',
      email: 'john.doe@domain.com',
      type: 'E',
      displayName: 'John Doe',
      password: 'SomethingSilly'
    }).then(function(user) {
      return Employer.create({
        city: 'Boston',
        phone_number: '+1 (734) DRAL',
        address: 'Astreet 89',
        state: 'Massachusetts',
        employer_description: 'I am an employer!',
        employer_picture: 'http://google.com/',
        UserId: user.id
      });
    }).then(function(employer) {
      return Business.create({
        business_name: 'Joblethics',
        business_address: 'Some street 75',
        business_city: 'Boston',
        business_state: 'Massachusetts',
        business_zip: 7123,
        business_description: 'A very good business',
        business_logo: 'https://lh3.googleusercontent.com/-02vOdc80_bQ/UZVL2172aMI/AAAAAAAAd70/ZSZLkwMKas8/s451-no/600573_10151235197458057_878851817_n.jpg',
        business_hiring_manager: 'Me'
      });
    }).then(function(business) {
      Listing.create({
        job_title: 'Barista',
        job_type: 'F',
        job_region: 'Boston',
        job_location: 'Exactly here',
        job_requirements: 'Some requirements',
        job_description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas eu felis et lorem venenatis consectetur. Suspendisse vestibulum ante id tortor venenatis ornare. Nullam aliquet, est sit amet ultrices feugiat, orci elit bibendum eros, quis molestie sem nisl pretium neque. Pellentesque sit amet justo sit amet eros fringilla maximus. Aliquam at felis eleifend est molestie tempus. Maecenas suscipit orci eu blandit efficitur. Aenean sit amet dictum mauris. Sed rutrum sapien a nibh tristique, eu tincidunt neque hendrerit. In ac lorem semper, molestie lectus ac, congue nulla. Phasellus nec semper tellus. Praesent egestas risus ante, in tincidunt ipsum faucibus ut. Sed porta ligula magna, non fermentum ex viverra ut.',
        job_compensation: 150,
        job_benefits: 'Some benefits',
        job_category: 'Barista',
        business_id: 1
      });
      return Candidate.create({
        phone_number: '916 741-3725',
        address: 'Hope ave 123 :P',
        state: 'Boston',
        skills: 'Good at doing stuff',
        headline: 'This is my tagline!',
        education: '[]',
        experience: '[]',
        birthday: '15-10-1996',
        email: 'm.c.dral@gmail.com',
        authorized: true,
        criminal: false,
        criminal_description: ''
      }).then(function(candidate) {
        return User.create({
          username: 'c@domain.com',
          email: 'c@domain.com',
          type: 'C',
          displayName: 'John Candidate',
          password: 'pass',
          candidate_id: candidate.id
        });
      });
    });
  };

}).call(this);
